# Generated by Django 4.1.7 on 2023-05-01 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='CreatedDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 1, 11, 35, 59, 236055), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
