# Generated by Django 4.1.7 on 2023-05-01 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_guest_createddate_alter_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('Apartment', models.CharField(max_length=150)),
                ('Governorate', models.CharField(max_length=50)),
                ('PostalCode', models.IntegerField(max_length=50, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='guest',
            name='CreatedDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 1, 15, 14, 27, 159822), editable=False),
        ),
    ]
