# Generated by Django 4.1.7 on 2023-05-02 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_guest_createddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('PatientID', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('c_age', models.CharField(blank=True, max_length=3, null=True)),
                ('Gender', models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male')], default='FEMALE', max_length=20)),
                ('Weight', models.CharField(blank=True, max_length=39, null=True)),
                ('Height', models.CharField(blank=True, max_length=39, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='X_ray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Bone_age', models.CharField(max_length=50)),
                ('Diagnosis', models.CharField(blank=True, max_length=50, null=True)),
                ('Notes', models.CharField(blank=True, max_length=50, null=True)),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.patient')),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='UserID',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='PickupLocations',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='DisplayName',
            new_name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='PromoCodeUsed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Role',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AddField(
            model_name='patient',
            name='DoctorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
