# Generated by Django 4.1.7 on 2023-05-02 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_patient_x_ray_remove_address_userid_delete_guest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_token_expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 2, 13, 45, 40, 516690, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
