# Generated by Django 4.1.7 on 2023-05-02 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_user_activation_token_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activation_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='activation_token_expiry',
        ),
        migrations.AddField(
            model_name='x_ray',
            name='Date',
            field=models.DateField(default=datetime.datetime(2023, 5, 2, 19, 11, 28, 444947, tzinfo=datetime.timezone.utc)),
        ),
    ]
